const DISTRICTS = {
  1: {
    adana: { name: 'Adana' },
    aladag: { name: 'Aladağ' },
    ceyhan: { name: 'Ceyhan' },
    cukurova: { name: 'Çukurova' },
    feke: { name: 'Feke' },
    imamoglu: { name: 'İmamoğlu' },
    karaisali: { name: 'Karaisalı' },
    karatas: { name: 'Karataş' },
    kozan: { name: 'Kozan' },
    pozanti: { name: 'Pozantı' },
    saimbeyli: { name: 'Saimbeyli' },
    saricam: { name: 'Sarıçam' },
    seyhan: { name: 'Seyhan' },
    tufanbeyli: { name: 'Tufanbeyli' },
    yumurtalik: { name: 'Yumurtalık' },
    yuregir: { name: 'Yüreğir' },
  },
  2: {
    adiyaman: { name: 'Adıyaman' },
    besni: { name: 'Besni' },
    celikhan: { name: 'Çelikhan' },
    gerger: { name: 'Gerger' },
    golbasi: { name: 'Gölbaşı' },
    kahta: { name: 'Kahta' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    samsat: { name: 'Samsat' },
    sincik: { name: 'Sincik' },
    tut: { name: 'Tut' },
  },
  3: {
    afyon: { name: 'Afyonkarahisar' },
    afyonkarahisar: { name: 'Afyonkarahisar' },
    basmakci: { name: 'Başmakçı' },
    bayat: { name: 'Bayat' },
    bolvadin: { name: 'Bolvadin' },
    cay: { name: 'Çay' },
    cobanlar: { name: 'Çobanlar' },
    dazkiri: { name: 'Dazkırı' },
    dinar: { name: 'Dinar' },
    emirdag: { name: 'Emirdağ' },
    evciler: { name: 'Evciler' },
    hocalar: { name: 'Hocalar' },
    ihsaniye: { name: 'İhsaniye' },
    iscehisar: { name: 'İscehisar' },
    kiziloren: { name: 'Kızılören' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    sandikli: { name: 'Sandıklı' },
    sinanpasa: { name: 'Sinanpaşa' },
    sultandagi: { name: 'Sultandağı' },
    suhut: { name: 'Şuhut' },
  },
  4: {
    agri: { name: 'Ağrı' },
    diyadin: { name: 'Diyadin' },
    dogubayazit: { name: 'Doğubayazıt' },
    eleskirt: { name: 'Eleşkirt' },
    hamur: { name: 'Hamur' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    patnos: { name: 'Patnos' },
    taslicay: { name: 'Taşlıçay' },
    tutak: { name: 'Tutak' },
  },
  5: {
    amasya: { name: 'Amasya' },
    goynucek: { name: 'Göynücek' },
    gumushacikoy: { name: 'Gümüşhacıköy' },
    hamamozu: { name: 'Hamamözü' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    merzifon: { name: 'Merzifon' },
    suluova: { name: 'Suluova' },
    tasova: { name: 'Taşova' },
  },
  6: {
    ankara: { name: 'Ankara' },
    akyurt: { name: 'Akyurt' },
    altindag: { name: 'Altındağ' },
    ayas: { name: 'Ayaş' },
    bala: { name: 'Bala' },
    beypazari: { name: 'Beypazarı' },
    camlidere: { name: 'Çamlıdere' },
    cankaya: { name: 'Çankaya' },
    cubuk: { name: 'Çubuk' },
    elmadag: { name: 'Elmadağ' },
    etimesgut: { name: 'Etimesgut' },
    evren: { name: 'Evren' },
    golbasi: { name: 'Gölbaşı' },
    gudul: { name: 'Güdül' },
    haymana: { name: 'Haymana' },
    kahramankazan: { name: 'Kahramankazan' },
    kalecik: { name: 'Kalecik' },
    kecioren: { name: 'Keçiören' },
    kizilcahamam: { name: 'Kızılcahamam' },
    mamak: { name: 'Mamak' },
    nallihan: { name: 'Nallıhan' },
    polatli: { name: 'Polatlı' },
    pursaklar: { name: 'Pursaklar' },
    sincan: { name: 'Sincan' },
    sereflikochisar: { name: 'Şereflikoçhisar' },
    yenimahalle: { name: 'Yenimahalle' },
  },
  7: {
    antalya: { name: 'Antalya' },
    akseki: { name: 'Akseki' },
    aksu: { name: 'Aksu' },
    alanya: { name: 'Alanya' },
    demre: { name: 'Demre' },
    dosemealti: { name: 'Döşemealtı' },
    elmali: { name: 'Elmalı' },
    finike: { name: 'Finike' },
    gazipasa: { name: 'Gazipaşa' },
    gundogmus: { name: 'Gündoğmuş' },
    ibradi: { name: 'İbradı' },
    kas: { name: 'Kaş' },
    kemer: { name: 'Kemer' },
    kepez: { name: 'Kepez' },
    konyaalti: { name: 'Konyaaltı' },
    korkuteli: { name: 'Korkuteli' },
    kumluca: { name: 'Kumluca' },
    manavgat: { name: 'Manavgat' },
    muratpasa: { name: 'Muratpaşa' },
    serik: { name: 'Serik' },
  },
  8: {
    artvin: { name: 'Artvin' },
    ardanuc: { name: 'Ardanuç' },
    arhavi: { name: 'Arhavi' },
    borcka: { name: 'Borçka' },
    hopa: { name: 'Hopa' },
    kemalpasa: { name: 'Kemalpaşa' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    murgul: { name: 'Murgul' },
    savsat: { name: 'Şavşat' },
    yusufeli: { name: 'Yusufeli' },
  },
  9: {
    aydin: { name: 'Aydın' },
    bozdogan: { name: 'Bozdoğan' },
    buharkent: { name: 'Buharkent' },
    cine: { name: 'Çine' },
    didim: { name: 'Didim' },
    efeler: { name: 'Efeler' },
    germencik: { name: 'Germencik' },
    incirliova: { name: 'İncirliova' },
    karacasu: { name: 'Karacasu' },
    karpuzlu: { name: 'Karpuzlu' },
    kocarli: { name: 'Koçarlı' },
    kosk: { name: 'Köşk' },
    kusadasi: { name: 'Kuşadası' },
    kuyucak: { name: 'Kuyucak' },
    nazilli: { name: 'Nazilli' },
    soke: { name: 'Söke' },
    sultanhisar: { name: 'Sultanhisar' },
    yenipazar: { name: 'Yenipazar' },
  },
  10: {
    balikesir: { name: 'Balıkesir' },
    altieylul: { name: 'Altıeylül' },
    ayvalik: { name: 'Ayvalık' },
    balya: { name: 'Balya' },
    bandirma: { name: 'Bandırma' },
    bigadic: { name: 'Bigadiç' },
    burhaniye: { name: 'Burhaniye' },
    dursunbey: { name: 'Dursunbey' },
    edremit: { name: 'Edremit' },
    erdek: { name: 'Erdek' },
    gomec: { name: 'Gömeç' },
    gonen: { name: 'Gönen' },
    havran: { name: 'Havran' },
    ivrindi: { name: 'İvrindi' },
    karesi: { name: 'Karesi' },
    kepsut: { name: 'Kepsut' },
    manyas: { name: 'Manyas' },
    marmara: { name: 'Marmara' },
    savastepe: { name: 'Savaştepe' },
    sindirgi: { name: 'Sındırgı' },
    susurluk: { name: 'Susurluk' },
  },
  11: {
    bilecik: { name: 'Bilecik' },
    bozuyuk: { name: 'Bozüyük' },
    golpazari: { name: 'Gölpazarı' },
    inhisar: { name: 'İnhisar' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    osmaneli: { name: 'Osmaneli' },
    pazaryeri: { name: 'Pazaryeri' },
    sogut: { name: 'Söğüt' },
    yenipazar: { name: 'Yenipazar' },
  },
  12: {
    bingol: { name: 'Bingöl' },
    adakli: { name: 'Adaklı' },
    genc: { name: 'Genç' },
    karliova: { name: 'Karlıova' },
    kigi: { name: 'Kiğı' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    solhan: { name: 'Solhan' },
    yayladere: { name: 'Yayladere' },
    yedisu: { name: 'Yedisu' },
  },
  13: {
    bitlis: { name: 'Bitlis' },
    adilcevaz: { name: 'Adilcevaz' },
    ahlat: { name: 'Ahlat' },
    guroymak: { name: 'Güroymak' },
    hizan: { name: 'Hizan' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    mutki: { name: 'Mutki' },
    tatvan: { name: 'Tatvan' },
  },
  14: {
    bolu: { name: 'Bolu' },
    dortdivan: { name: 'Dörtdivan' },
    gerede: { name: 'Gerede' },
    goynuk: { name: 'Göynük' },
    kibriscik: { name: 'Kıbrıscık' },
    mengen: { name: 'Mengen' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    mudurnu: { name: 'Mudurnu' },
    seben: { name: 'Seben' },
    yenicaga: { name: 'Yeniçağa' },
  },
  15: {
    burdur: { name: 'Burdur' },
    aglasun: { name: 'Ağlasun' },
    altinyayla: { name: 'Altınyayla' },
    bucak: { name: 'Bucak' },
    cavdir: { name: 'Çavdır' },
    celtikci: { name: 'Çeltikçi' },
    golhisar: { name: 'Gölhisar' },
    karamanli: { name: 'Karamanlı' },
    kemer: { name: 'Kemer' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    tefenni: { name: 'Tefenni' },
    yesilova: { name: 'Yeşilova' },
  },
  16: {
    bursa: { name: 'Bursa' },
    buyukorhan: { name: 'Büyükorhan' },
    gemlik: { name: 'Gemlik' },
    gursu: { name: 'Gürsu' },
    harmancik: { name: 'Harmancık' },
    inegol: { name: 'İnegöl' },
    iznik: { name: 'İznik' },
    karacabey: { name: 'Karacabey' },
    keles: { name: 'Keles' },
    kestel: { name: 'Kestel' },
    mudanya: { name: 'Mudanya' },
    mustafakemalpasa: { name: 'Mustafakemalpaşa' },
    nilufer: { name: 'Nilüfer' },
    orhaneli: { name: 'Orhaneli' },
    orhangazi: { name: 'Orhangazi' },
    osmangazi: { name: 'Osmangazi' },
    yenisehir: { name: 'Yenişehir' },
    yildirim: { name: 'Yıldırım' },
  },
  17: {
    canakkale: { name: 'Çanakkale' },
    ayvacik: { name: 'Ayvacık' },
    bayramic: { name: 'Bayramiç' },
    biga: { name: 'Biga' },
    bozcaada: { name: 'Bozcaada' },
    can: { name: 'Çan' },
    eceabat: { name: 'Eceabat' },
    ezine: { name: 'Ezine' },
    gelibolu: { name: 'Gelibolu' },
    gokceada: { name: 'Gökçeada' },
    lapseki: { name: 'Lapseki' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    yenice: { name: 'Yenice' },
  },
  18: {
    cankiri: { name: 'Çankırı' },
    atkaracalar: { name: 'Atkaracalar' },
    bayramoren: { name: 'Bayramören' },
    cerkes: { name: 'Çerkeş' },
    eldivan: { name: 'Eldivan' },
    ilgaz: { name: 'Ilgaz' },
    kizilirmak: { name: 'Kızılırmak' },
    korgun: { name: 'Korgun' },
    kursunlu: { name: 'Kurşunlu' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    orta: { name: 'Orta' },
    sabanozu: { name: 'Şabanözü' },
    yaprakli: { name: 'Yapraklı' },
  },
  19: {
    corum: { name: 'Çorum' },
    alaca: { name: 'Alaca' },
    bayat: { name: 'Bayat' },
    bogazkale: { name: 'Boğazkale' },
    dodurga: { name: 'Dodurga' },
    iskilip: { name: 'İskilip' },
    kargi: { name: 'Kargı' },
    lacin: { name: 'Laçin' },
    mecitozu: { name: 'Mecitözü' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    oguzlar: { name: 'Oğuzlar' },
    ortakoy: { name: 'Ortaköy' },
    osmancik: { name: 'Osmancık' },
    sungurlu: { name: 'Sungurlu' },
    ugurludag: { name: 'Uğurludağ' },
  },
  20: {
    denizli: { name: 'Denizli' },
    acipayam: { name: 'Acıpayam' },
    babadag: { name: 'Babadağ' },
    baklan: { name: 'Baklan' },
    bekilli: { name: 'Bekilli' },
    beyagac: { name: 'Beyağaç' },
    bozkurt: { name: 'Bozkurt' },
    buldan: { name: 'Buldan' },
    cal: { name: 'Çal' },
    cameli: { name: 'Çameli' },
    cardak: { name: 'Çardak' },
    civril: { name: 'Çivril' },
    guney: { name: 'Güney' },
    honaz: { name: 'Honaz' },
    kale: { name: 'Kale' },
    merkezefendi: { name: 'Merkezefendi' },
    pamukkale: { name: 'Pamukkale' },
    saraykoy: { name: 'Sarayköy' },
    serinhisar: { name: 'Serinhisar' },
    tavas: { name: 'Tavas' },
  },
  21: {
    diyarbakir: { name: 'Diyarbakır' },
    baglar: { name: 'Bağlar' },
    bismil: { name: 'Bismil' },
    cermik: { name: 'Çermik' },
    cinar: { name: 'Çınar' },
    cungus: { name: 'Çüngüş' },
    dicle: { name: 'Dicle' },
    egil: { name: 'Eğil' },
    ergani: { name: 'Ergani' },
    hani: { name: 'Hani' },
    hazro: { name: 'Hazro' },
    kayapinar: { name: 'Kayapınar' },
    kocakoy: { name: 'Kocaköy' },
    kulp: { name: 'Kulp' },
    lice: { name: 'Lice' },
    silvan: { name: 'Silvan' },
    sur: { name: 'Sur' },
    yenisehir: { name: 'Yenişehir' },
  },
  22: {
    edirne: { name: 'Edirne' },
    enez: { name: 'Enez' },
    havsa: { name: 'Havsa' },
    ipsala: { name: 'İpsala' },
    kesan: { name: 'Keşan' },
    lalapasa: { name: 'Lalapaşa' },
    meric: { name: 'Meriç' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    suloglu: { name: 'Süloğlu' },
    uzunkopru: { name: 'Uzunköprü' },
  },
  23: {
    elazig: { name: 'Elazığ' },
    agin: { name: 'Ağın' },
    alacakaya: { name: 'Alacakaya' },
    aricak: { name: 'Arıcak' },
    baskil: { name: 'Baskil' },
    karakocan: { name: 'Karakoçan' },
    keban: { name: 'Keban' },
    kovancilar: { name: 'Kovancılar' },
    maden: { name: 'Maden' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    palu: { name: 'Palu' },
    sivrice: { name: 'Sivrice' },
  },
  24: {
    erzincan: { name: 'Erzincan' },
    cayirli: { name: 'Çayırlı' },
    ilic: { name: 'İliç' },
    kemah: { name: 'Kemah' },
    kemaliye: { name: 'Kemaliye' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    otlukbeli: { name: 'Otlukbeli' },
    refahiye: { name: 'Refahiye' },
    tercan: { name: 'Tercan' },
    uzumlu: { name: 'Üzümlü' },
  },
  25: {
    erzurum: { name: 'Erzurum' },
    askale: { name: 'Aşkale' },
    aziziye: { name: 'Aziziye' },
    cat: { name: 'Çat' },
    hinis: { name: 'Hınıs' },
    horasan: { name: 'Horasan' },
    ispir: { name: 'İspir' },
    karacoban: { name: 'Karaçoban' },
    karayazi: { name: 'Karayazı' },
    koprukoy: { name: 'Köprüköy' },
    narman: { name: 'Narman' },
    oltu: { name: 'Oltu' },
    olur: { name: 'Olur' },
    palandoken: { name: 'Palandöken' },
    pasinler: { name: 'Pasinler' },
    pazaryolu: { name: 'Pazaryolu' },
    senkaya: { name: 'Şenkaya' },
    tekman: { name: 'Tekman' },
    tortum: { name: 'Tortum' },
    uzundere: { name: 'Uzundere' },
    yakutiye: { name: 'Yakutiye' },
  },
  26: {
    eskisehir: { name: 'Eskişehir' },
    alpu: { name: 'Alpu' },
    beylikova: { name: 'Beylikova' },
    cifteler: { name: 'Çifteler' },
    gunyuzu: { name: 'Günyüzü' },
    han: { name: 'Han' },
    inonu: { name: 'İnönü' },
    mahmudiye: { name: 'Mahmudiye' },
    mihalgazi: { name: 'Mihalgazi' },
    mihaliccik: { name: 'Mihalıççık' },
    odunpazari: { name: 'Odunpazarı' },
    saricakaya: { name: 'Sarıcakaya' },
    seyitgazi: { name: 'Seyitgazi' },
    sivrihisar: { name: 'Sivrihisar' },
    tepebasi: { name: 'Tepebaşı' },
  },
  27: {
    gaziantep: { name: 'Gaziantep' },
    antep: { name: 'Gaziantep' },
    araban: { name: 'Araban' },
    islahiye: { name: 'İslahiye' },
    karkamis: { name: 'Karkamış' },
    nizip: { name: 'Nizip' },
    nurdagi: { name: 'Nurdağı' },
    oguzeli: { name: 'Oğuzeli' },
    sahinbey: { name: 'Şahinbey' },
    sehitkamil: { name: 'Şehitkamil' },
    yavuzeli: { name: 'Yavuzeli' },
  },
  28: {
    giresun: { name: 'Giresun' },
    alucra: { name: 'Alucra' },
    bulancak: { name: 'Bulancak' },
    camoluk: { name: 'Çamoluk' },
    canakci: { name: 'Çanakçı' },
    dereli: { name: 'Dereli' },
    dogankent: { name: 'Doğankent' },
    espiye: { name: 'Espiye' },
    eynesil: { name: 'Eynesil' },
    gorele: { name: 'Görele' },
    guce: { name: 'Güce' },
    kesap: { name: 'Keşap' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    piraziz: { name: 'Piraziz' },
    sebinkarahisar: { name: 'Şebinkarahisar' },
    tirebolu: { name: 'Tirebolu' },
    yaglidere: { name: 'Yağlıdere' },
  },
  29: {
    gumushane: { name: 'Gümüşhane' },
    kelkit: { name: 'Kelkit' },
    kose: { name: 'Köse' },
    kurtun: { name: 'Kürtün' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    siran: { name: 'Şiran' },
    torul: { name: 'Torul' },
  },
  30: {
    hakkari: { name: 'Hakkari' },
    cukurca: { name: 'Çukurca' },
    derecik: { name: 'Derecik' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    semdinli: { name: 'Şemdinli' },
    yuksekova: { name: 'Yüksekova' },
  },
  31: {
    hatay: { name: 'Hatay' },
    altinozu: { name: 'Altınözü' },
    antakya: { name: 'Antakya' },
    arsuz: { name: 'Arsuz' },
    belen: { name: 'Belen' },
    defne: { name: 'Defne' },
    dortyol: { name: 'Dörtyol' },
    erzin: { name: 'Erzin' },
    hassa: { name: 'Hassa' },
    iskenderun: { name: 'İskenderun' },
    kirikhan: { name: 'Kırıkhan' },
    kumlu: { name: 'Kumlu' },
    payas: { name: 'Payas' },
    reyhanli: { name: 'Reyhanlı' },
    samandag: { name: 'Samandağ' },
    yayladagi: { name: 'Yayladağı' },
  },
  32: {
    isparta: { name: 'Isparta' },
    aksu: { name: 'Aksu' },
    atabey: { name: 'Atabey' },
    egirdir: { name: 'Eğirdir' },
    gelendost: { name: 'Gelendost' },
    gonen: { name: 'Gönen' },
    keciborlu: { name: 'Keçiborlu' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    senirkent: { name: 'Senirkent' },
    sutculer: { name: 'Sütçüler' },
    sarkikaraagac: { name: 'Şarkikaraağaç' },
    uluborlu: { name: 'Uluborlu' },
    yalvac: { name: 'Yalvaç' },
    yenisarbademli: { name: 'Yenişarbademli' },
  },
  33: {
    mersin: { name: 'Mersin' },
    akdeniz: { name: 'Akdeniz' },
    anamur: { name: 'Anamur' },
    aydincik: { name: 'Aydıncık' },
    bozyazi: { name: 'Bozyazı' },
    camliyayla: { name: 'Çamlıyayla' },
    erdemli: { name: 'Erdemli' },
    gulnar: { name: 'Gülnar' },
    mezitli: { name: 'Mezitli' },
    mut: { name: 'Mut' },
    silifke: { name: 'Silifke' },
    tarsus: { name: 'Tarsus' },
    toroslar: { name: 'Toroslar' },
    yenisehir: { name: 'Yenişehir' },
  },
  34: {
    'istanbul anadolu': { name: 'İstanbul' },
    'istanbul avrupa': { name: 'İstanbul' },
    istanbul: { name: 'İstanbul' },
    adalar: { name: 'Adalar' },
    arnavutkoy: { name: 'Arnavutköy' },
    atasehir: { name: 'Ataşehir' },
    avcilar: { name: 'Avcılar' },
    bagcilar: { name: 'Bağcılar' },
    bahcelievler: { name: 'Bahçelievler' },
    bakirkoy: { name: 'Bakırköy' },
    basaksehir: { name: 'Başakşehir' },
    bayrampasa: { name: 'Bayrampaşa' },
    besiktas: { name: 'Beşiktaş' },
    beykoz: { name: 'Beykoz' },
    beylikduzu: { name: 'Beylikdüzü' },
    beyoglu: { name: 'Beyoğlu' },
    buyukcekmece: { name: 'Büyükçekmece' },
    catalca: { name: 'Çatalca' },
    cekmekoy: { name: 'Çekmeköy' },
    esenler: { name: 'Esenler' },
    esenyurt: { name: 'Esenyurt' },
    eyupsultan: { name: 'Eyüpsultan' },
    fatih: { name: 'Fatih' },
    gaziosmanpasa: { name: 'Gaziosmanpaşa' },
    gungoren: { name: 'Güngören' },
    kadikoy: { name: 'Kadıköy' },
    kagithane: { name: 'Kağıthane' },
    kartal: { name: 'Kartal' },
    kucukcekmece: { name: 'Küçükçekmece' },
    maltepe: { name: 'Maltepe' },
    pendik: { name: 'Pendik' },
    sancaktepe: { name: 'Sancaktepe' },
    sariyer: { name: 'Sarıyer' },
    silivri: { name: 'Silivri' },
    sultanbeyli: { name: 'Sultanbeyli' },
    sultangazi: { name: 'Sultangazi' },
    sile: { name: 'Şile' },
    sisli: { name: 'Şişli' },
    tuzla: { name: 'Tuzla' },
    umraniye: { name: 'Ümraniye' },
    uskudar: { name: 'Üsküdar' },
    zeytinburnu: { name: 'Zeytinburnu' },
  },
  35: {
    izmir: { name: 'İzmir' },
    aliaga: { name: 'Aliağa' },
    balcova: { name: 'Balçova' },
    bayindir: { name: 'Bayındır' },
    bayrakli: { name: 'Bayraklı' },
    bergama: { name: 'Bergama' },
    beydag: { name: 'Beydağ' },
    bornova: { name: 'Bornova' },
    buca: { name: 'Buca' },
    cesme: { name: 'Çeşme' },
    cigli: { name: 'Çiğli' },
    dikili: { name: 'Dikili' },
    foca: { name: 'Foça' },
    gaziemir: { name: 'Gaziemir' },
    guzelbahce: { name: 'Güzelbahçe' },
    karabaglar: { name: 'Karabağlar' },
    karaburun: { name: 'Karaburun' },
    karsiyaka: { name: 'Karşıyaka' },
    kemalpasa: { name: 'Kemalpaşa' },
    kinik: { name: 'Kınık' },
    kiraz: { name: 'Kiraz' },
    konak: { name: 'Konak' },
    menderes: { name: 'Menderes' },
    menemen: { name: 'Menemen' },
    narlidere: { name: 'Narlıdere' },
    odemis: { name: 'Ödemiş' },
    seferihisar: { name: 'Seferihisar' },
    selcuk: { name: 'Selçuk' },
    tire: { name: 'Tire' },
    torbali: { name: 'Torbalı' },
    urla: { name: 'Urla' },
  },
  36: {
    kars: { name: 'Kars' },
    akyaka: { name: 'Akyaka' },
    arpacay: { name: 'Arpaçay' },
    digor: { name: 'Digor' },
    kagizman: { name: 'Kağızman' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    sarikamis: { name: 'Sarıkamış' },
    selim: { name: 'Selim' },
    susuz: { name: 'Susuz' },
  },
  37: {
    kastamonu: { name: 'Kastamonu' },
    abana: { name: 'Abana' },
    agli: { name: 'Ağlı' },
    arac: { name: 'Araç' },
    azdavay: { name: 'Azdavay' },
    bozkurt: { name: 'Bozkurt' },
    cide: { name: 'Cide' },
    catalzeytin: { name: 'Çatalzeytin' },
    daday: { name: 'Daday' },
    devrekani: { name: 'Devrekani' },
    doganyurt: { name: 'Doğanyurt' },
    hanonu: { name: 'Hanönü' },
    ihsangazi: { name: 'İhsangazi' },
    inebolu: { name: 'İnebolu' },
    kure: { name: 'Küre' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    pinarbasi: { name: 'Pınarbaşı' },
    seydiler: { name: 'Seydiler' },
    senpazar: { name: 'Şenpazar' },
    taskopru: { name: 'Taşköprü' },
    tosya: { name: 'Tosya' },
  },
  38: {
    kayseri: { name: 'Kayseri' },
    akkisla: { name: 'Akkışla' },
    bunyan: { name: 'Bünyan' },
    develi: { name: 'Develi' },
    felahiye: { name: 'Felahiye' },
    hacilar: { name: 'Hacılar' },
    incesu: { name: 'İncesu' },
    kocasinan: { name: 'Kocasinan' },
    melikgazi: { name: 'Melikgazi' },
    ozvatan: { name: 'Özvatan' },
    pinarbasi: { name: 'Pınarbaşı' },
    sarioglan: { name: 'Sarıoğlan' },
    sariz: { name: 'Sarız' },
    talas: { name: 'Talas' },
    tomarza: { name: 'Tomarza' },
    yahyali: { name: 'Yahyalı' },
    yesilhisar: { name: 'Yeşilhisar' },
  },
  39: {
    kirklareli: { name: 'Kırklareli' },
    babaeski: { name: 'Babaeski' },
    demirkoy: { name: 'Demirköy' },
    kofcaz: { name: 'Kofçaz' },
    luleburgaz: { name: 'Lüleburgaz' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    pehlivankoy: { name: 'Pehlivanköy' },
    pinarhisar: { name: 'Pınarhisar' },
    vize: { name: 'Vize' },
  },
  40: {
    kirsehir: { name: 'Kırşehir' },
    akcakent: { name: 'Akçakent' },
    akpinar: { name: 'Akpınar' },
    boztepe: { name: 'Boztepe' },
    cicekdagi: { name: 'Çiçekdağı' },
    kaman: { name: 'Kaman' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    mucur: { name: 'Mucur' },
  },
  41: {
    kocaeli: { name: 'Kocaeli' },
    basiskele: { name: 'Başiskele' },
    cayirova: { name: 'Çayırova' },
    darica: { name: 'Darıca' },
    derince: { name: 'Derince' },
    dilovasi: { name: 'Dilovası' },
    gebze: { name: 'Gebze' },
    golcuk: { name: 'Gölcük' },
    izmit: { name: 'İzmit' },
    kandira: { name: 'Kandıra' },
    karamursel: { name: 'Karamürsel' },
    kartepe: { name: 'Kartepe' },
    korfez: { name: 'Körfez' },
  },
  42: {
    konya: { name: 'Konya' },
    ahirli: { name: 'Ahırlı' },
    akoren: { name: 'Akören' },
    aksehir: { name: 'Akşehir' },
    altinekin: { name: 'Altınekin' },
    beysehir: { name: 'Beyşehir' },
    bozkir: { name: 'Bozkır' },
    cihanbeyli: { name: 'Cihanbeyli' },
    celtik: { name: 'Çeltik' },
    cumra: { name: 'Çumra' },
    derbent: { name: 'Derbent' },
    derebucak: { name: 'Derebucak' },
    doganhisar: { name: 'Doğanhisar' },
    emirgazi: { name: 'Emirgazi' },
    eregli: { name: 'Ereğli' },
    guneysinir: { name: 'Güneysınır' },
    hadim: { name: 'Hadim' },
    halkapinar: { name: 'Halkapınar' },
    huyuk: { name: 'Hüyük' },
    ilgin: { name: 'Ilgın' },
    kadinhani: { name: 'Kadınhanı' },
    karapinar: { name: 'Karapınar' },
    karatay: { name: 'Karatay' },
    kulu: { name: 'Kulu' },
    meram: { name: 'Meram' },
    sarayonu: { name: 'Sarayönü' },
    selcuklu: { name: 'Selçuklu' },
    seydisehir: { name: 'Seydişehir' },
    taskent: { name: 'Taşkent' },
    tuzlukcu: { name: 'Tuzlukçu' },
    yalihuyuk: { name: 'Yalıhüyük' },
    yunak: { name: 'Yunak' },
  },
  43: {
    kutahya: { name: 'Kütahya' },
    altintas: { name: 'Altıntaş' },
    aslanapa: { name: 'Aslanapa' },
    cavdarhisar: { name: 'Çavdarhisar' },
    domanic: { name: 'Domaniç' },
    dumlupinar: { name: 'Dumlupınar' },
    emet: { name: 'Emet' },
    gediz: { name: 'Gediz' },
    hisarcik: { name: 'Hisarcık' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    pazarlar: { name: 'Pazarlar' },
    simav: { name: 'Simav' },
    saphane: { name: 'Şaphane' },
    tavsanli: { name: 'Tavşanlı' },
  },
  44: {
    malatya: { name: 'Malatya' },
    akcadag: { name: 'Akçadağ' },
    arapgir: { name: 'Arapgir' },
    arguvan: { name: 'Arguvan' },
    battalgazi: { name: 'Battalgazi' },
    darende: { name: 'Darende' },
    dogansehir: { name: 'Doğanşehir' },
    doganyol: { name: 'Doğanyol' },
    hekimhan: { name: 'Hekimhan' },
    kale: { name: 'Kale' },
    kuluncak: { name: 'Kuluncak' },
    puturge: { name: 'Pütürge' },
    yazihan: { name: 'Yazıhan' },
    yesilyurt: { name: 'Yeşilyurt' },
  },
  45: {
    manisa: { name: 'Manisa' },
    ahmetli: { name: 'Ahmetli' },
    akhisar: { name: 'Akhisar' },
    alasehir: { name: 'Alaşehir' },
    demirci: { name: 'Demirci' },
    golmarmara: { name: 'Gölmarmara' },
    gordes: { name: 'Gördes' },
    kirkagac: { name: 'Kırkağaç' },
    koprubasi: { name: 'Köprübaşı' },
    kula: { name: 'Kula' },
    salihli: { name: 'Salihli' },
    sarigol: { name: 'Sarıgöl' },
    saruhanli: { name: 'Saruhanlı' },
    selendi: { name: 'Selendi' },
    soma: { name: 'Soma' },
    sehzadeler: { name: 'Şehzadeler' },
    turgutlu: { name: 'Turgutlu' },
    yunusemre: { name: 'Yunusemre' },
  },
  46: {
    kahramanmaras: { name: 'Kahramanmaraş' },
    maras: { name: 'Kahramanmaraş' },
    afsin: { name: 'Afşin' },
    andirin: { name: 'Andırın' },
    caglayancerit: { name: 'Çağlayancerit' },
    dulkadiroglu: { name: 'Dulkadiroğlu' },
    ekinozu: { name: 'Ekinözü' },
    elbistan: { name: 'Elbistan' },
    goksun: { name: 'Göksun' },
    nurhak: { name: 'Nurhak' },
    onikisubat: { name: 'Onikişubat' },
    pazarcik: { name: 'Pazarcık' },
    turkoglu: { name: 'Türkoğlu' },
  },
  47: {
    mardin: { name: 'Mardin' },
    artuklu: { name: 'Artuklu' },
    dargecit: { name: 'Dargeçit' },
    derik: { name: 'Derik' },
    kiziltepe: { name: 'Kızıltepe' },
    mazidagi: { name: 'Mazıdağı' },
    midyat: { name: 'Midyat' },
    nusaybin: { name: 'Nusaybin' },
    omerli: { name: 'Ömerli' },
    savur: { name: 'Savur' },
    yesilli: { name: 'Yeşilli' },
  },
  48: {
    mugla: { name: 'Muğla' },
    bodrum: { name: 'Bodrum' },
    dalaman: { name: 'Dalaman' },
    datca: { name: 'Datça' },
    fethiye: { name: 'Fethiye' },
    kavaklidere: { name: 'Kavaklıdere' },
    koycegiz: { name: 'Köyceğiz' },
    marmaris: { name: 'Marmaris' },
    mentese: { name: 'Menteşe' },
    milas: { name: 'Milas' },
    ortaca: { name: 'Ortaca' },
    seydikemer: { name: 'Seydikemer' },
    ula: { name: 'Ula' },
    yatagan: { name: 'Yatağan' },
  },
  49: {
    mus: { name: 'Muş' },
    bulanik: { name: 'Bulanık' },
    haskoy: { name: 'Hasköy' },
    korkut: { name: 'Korkut' },
    malazgirt: { name: 'Malazgirt' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    varto: { name: 'Varto' },
  },
  50: {
    nevsehir: { name: 'Nevşehir' },
    acigol: { name: 'Acıgöl' },
    avanos: { name: 'Avanos' },
    derinkuyu: { name: 'Derinkuyu' },
    gulsehir: { name: 'Gülşehir' },
    hacibektas: { name: 'Hacıbektaş' },
    kozakli: { name: 'Kozaklı' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    urgup: { name: 'Ürgüp' },
  },
  51: {
    nigde: { name: 'Niğde' },
    altunhisar: { name: 'Altunhisar' },
    bor: { name: 'Bor' },
    camardi: { name: 'Çamardı' },
    ciftlik: { name: 'Çiftlik' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    ulukisla: { name: 'Ulukışla' },
  },
  52: {
    ordu: { name: 'Ordu' },
    akkus: { name: 'Akkuş' },
    altinordu: { name: 'Altınordu' },
    aybasti: { name: 'Aybastı' },
    camas: { name: 'Çamaş' },
    catalpinar: { name: 'Çatalpınar' },
    caybasi: { name: 'Çaybaşı' },
    fatsa: { name: 'Fatsa' },
    golkoy: { name: 'Gölköy' },
    gulyali: { name: 'Gülyalı' },
    gurgentepe: { name: 'Gürgentepe' },
    ikizce: { name: 'İkizce' },
    kabaduz: { name: 'Kabadüz' },
    kabatas: { name: 'Kabataş' },
    korgan: { name: 'Korgan' },
    kumru: { name: 'Kumru' },
    mesudiye: { name: 'Mesudiye' },
    persembe: { name: 'Perşembe' },
    ulubey: { name: 'Ulubey' },
    unye: { name: 'Ünye' },
  },
  53: {
    rize: { name: 'Rize' },
    ardesen: { name: 'Ardeşen' },
    camlihemsin: { name: 'Çamlıhemşin' },
    cayeli: { name: 'Çayeli' },
    derepazari: { name: 'Derepazarı' },
    findikli: { name: 'Fındıklı' },
    guneysu: { name: 'Güneysu' },
    hemsin: { name: 'Hemşin' },
    ikizdere: { name: 'İkizdere' },
    iyidere: { name: 'İyidere' },
    kalkandere: { name: 'Kalkandere' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    pazar: { name: 'Pazar' },
  },
  54: {
    sakarya: { name: 'Sakarya' },
    adapazari: { name: 'Adapazarı' },
    akyazi: { name: 'Akyazı' },
    arifiye: { name: 'Arifiye' },
    erenler: { name: 'Erenler' },
    ferizli: { name: 'Ferizli' },
    geyve: { name: 'Geyve' },
    hendek: { name: 'Hendek' },
    karapurcek: { name: 'Karapürçek' },
    karasu: { name: 'Karasu' },
    kaynarca: { name: 'Kaynarca' },
    kocaali: { name: 'Kocaali' },
    pamukova: { name: 'Pamukova' },
    sapanca: { name: 'Sapanca' },
    serdivan: { name: 'Serdivan' },
    sogutlu: { name: 'Söğütlü' },
    tarakli: { name: 'Taraklı' },
  },
  55: {
    samsun: { name: 'Samsun' },
    '19 mayis': { name: '19 Mayıs' },
    alacam: { name: 'Alaçam' },
    asarcik: { name: 'Asarcık' },
    atakum: { name: 'Atakum' },
    ayvacik: { name: 'Ayvacık' },
    bafra: { name: 'Bafra' },
    canik: { name: 'Canik' },
    carsamba: { name: 'Çarşamba' },
    havza: { name: 'Havza' },
    ilkadim: { name: 'İlkadım' },
    kavak: { name: 'Kavak' },
    ladik: { name: 'Ladik' },
    salipazari: { name: 'Salıpazarı' },
    tekkekoy: { name: 'Tekkeköy' },
    terme: { name: 'Terme' },
    vezirkopru: { name: 'Vezirköprü' },
    yakakent: { name: 'Yakakent' },
  },
  56: {
    siirt: { name: 'Siirt' },
    baykan: { name: 'Baykan' },
    eruh: { name: 'Eruh' },
    kurtalan: { name: 'Kurtalan' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    pervari: { name: 'Pervari' },
    sirvan: { name: 'Şirvan' },
    tillo: { name: 'Tillo' },
  },
  57: {
    sinop: { name: 'Sinop' },
    ayancik: { name: 'Ayancık' },
    boyabat: { name: 'Boyabat' },
    dikmen: { name: 'Dikmen' },
    duragan: { name: 'Durağan' },
    erfelek: { name: 'Erfelek' },
    gerze: { name: 'Gerze' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    sarayduzu: { name: 'Saraydüzü' },
    turkeli: { name: 'Türkeli' },
  },
  58: {
    sivas: { name: 'Sivas' },
    akincilar: { name: 'Akıncılar' },
    altinyayla: { name: 'Altınyayla' },
    divrigi: { name: 'Divriği' },
    dogansar: { name: 'Doğanşar' },
    gemerek: { name: 'Gemerek' },
    golova: { name: 'Gölova' },
    gurun: { name: 'Gürün' },
    hafik: { name: 'Hafik' },
    imranli: { name: 'İmranlı' },
    kangal: { name: 'Kangal' },
    koyulhisar: { name: 'Koyulhisar' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    susehri: { name: 'Suşehri' },
    sarkisla: { name: 'Şarkışla' },
    ulas: { name: 'Ulaş' },
    yildizeli: { name: 'Yıldızeli' },
    zara: { name: 'Zara' },
  },
  59: {
    tekirdag: { name: 'Tekirdağ' },
    cerkezkoy: { name: 'Çerkezköy' },
    corlu: { name: 'Çorlu' },
    ergene: { name: 'Ergene' },
    hayrabolu: { name: 'Hayrabolu' },
    kapakli: { name: 'Kapaklı' },
    malkara: { name: 'Malkara' },
    marmaraereglisi: { name: 'Marmaraereğlisi' },
    muratli: { name: 'Muratlı' },
    saray: { name: 'Saray' },
    suleymanpasa: { name: 'Süleymanpaşa' },
    sarkoy: { name: 'Şarköy' },
  },
  60: {
    tokat: { name: 'Tokat' },
    almus: { name: 'Almus' },
    artova: { name: 'Artova' },
    basciftlik: { name: 'Başçiftlik' },
    erbaa: { name: 'Erbaa' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    niksar: { name: 'Niksar' },
    pazar: { name: 'Pazar' },
    resadiye: { name: 'Reşadiye' },
    sulusaray: { name: 'Sulusaray' },
    turhal: { name: 'Turhal' },
    yesilyurt: { name: 'Yeşilyurt' },
    zile: { name: 'Zile' },
  },
  61: {
    trabzon: { name: 'Trabzon' },
    akcaabat: { name: 'Akçaabat' },
    arakli: { name: 'Araklı' },
    arsin: { name: 'Arsin' },
    besikduzu: { name: 'Beşikdüzü' },
    carsibasi: { name: 'Çarşıbaşı' },
    caykara: { name: 'Çaykara' },
    dernekpazari: { name: 'Dernekpazarı' },
    duzkoy: { name: 'Düzköy' },
    hayrat: { name: 'Hayrat' },
    koprubasi: { name: 'Köprübaşı' },
    macka: { name: 'Maçka' },
    of: { name: 'Of' },
    ortahisar: { name: 'Ortahisar' },
    surmene: { name: 'Sürmene' },
    salpazari: { name: 'Şalpazarı' },
    tonya: { name: 'Tonya' },
    vakfikebir: { name: 'Vakfıkebir' },
    yomra: { name: 'Yomra' },
  },
  62: {
    tunceli: { name: 'Tunceli' },
    cemisgezek: { name: 'Çemişgezek' },
    hozat: { name: 'Hozat' },
    mazgirt: { name: 'Mazgirt' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    nazimiye: { name: 'Nazımiye' },
    ovacik: { name: 'Ovacık' },
    pertek: { name: 'Pertek' },
    pulumur: { name: 'Pülümür' },
  },
  63: {
    sanliurfa: { name: 'Şanlıurfa' },
    urfa: { name: 'Şanlıurfa' },
    akcakale: { name: 'Akçakale' },
    birecik: { name: 'Birecik' },
    bozova: { name: 'Bozova' },
    ceylanpinar: { name: 'Ceylanpınar' },
    eyyubiye: { name: 'Eyyübiye' },
    halfeti: { name: 'Halfeti' },
    haliliye: { name: 'Haliliye' },
    harran: { name: 'Harran' },
    hilvan: { name: 'Hilvan' },
    karakopru: { name: 'Karaköprü' },
    siverek: { name: 'Siverek' },
    suruc: { name: 'Suruç' },
    viransehir: { name: 'Viranşehir' },
  },
  64: {
    usak: { name: 'Uşak' },
    banaz: { name: 'Banaz' },
    esme: { name: 'Eşme' },
    karahalli: { name: 'Karahallı' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    sivasli: { name: 'Sivaslı' },
    ulubey: { name: 'Ulubey' },
  },
  65: {
    van: { name: 'Van' },
    bahcesaray: { name: 'Bahçesaray' },
    baskale: { name: 'Başkale' },
    caldiran: { name: 'Çaldıran' },
    catak: { name: 'Çatak' },
    edremit: { name: 'Edremit' },
    ercis: { name: 'Erciş' },
    gevas: { name: 'Gevaş' },
    gurpinar: { name: 'Gürpınar' },
    ipekyolu: { name: 'İpekyolu' },
    muradiye: { name: 'Muradiye' },
    ozalp: { name: 'Özalp' },
    saray: { name: 'Saray' },
    tusba: { name: 'Tuşba' },
  },
  66: {
    yozgat: { name: 'Yozgat' },
    akdagmadeni: { name: 'Akdağmadeni' },
    aydincik: { name: 'Aydıncık' },
    bogazliyan: { name: 'Boğazlıyan' },
    candir: { name: 'Çandır' },
    cayiralan: { name: 'Çayıralan' },
    cekerek: { name: 'Çekerek' },
    kadisehri: { name: 'Kadışehri' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    saraykent: { name: 'Saraykent' },
    sarikaya: { name: 'Sarıkaya' },
    sorgun: { name: 'Sorgun' },
    sefaatli: { name: 'Şefaatli' },
    yenifakili: { name: 'Yenifakılı' },
    yerkoy: { name: 'Yerköy' },
  },
  67: {
    zonguldak: { name: 'Zonguldak' },
    alapli: { name: 'Alaplı' },
    caycuma: { name: 'Çaycuma' },
    devrek: { name: 'Devrek' },
    eregli: { name: 'Ereğli' },
    gokcebey: { name: 'Gökçebey' },
    kilimli: { name: 'Kilimli' },
    kozlu: { name: 'Kozlu' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
  },
  68: {
    aksaray: { name: 'Aksaray' },
    agacoren: { name: 'Ağaçören' },
    eskil: { name: 'Eskil' },
    gulagac: { name: 'Gülağaç' },
    guzelyurt: { name: 'Güzelyurt' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    ortakoy: { name: 'Ortaköy' },
    sariyahsi: { name: 'Sarıyahşi' },
    sultanhani: { name: 'Sultanhanı' },
  },
  69: {
    bayburt: { name: 'Bayburt' },
    aydintepe: { name: 'Aydıntepe' },
    demirozu: { name: 'Demirözü' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
  },
  70: {
    karaman: { name: 'Karaman' },
    ayranci: { name: 'Ayrancı' },
    basyayla: { name: 'Başyayla' },
    ermenek: { name: 'Ermenek' },
    kazimkarabekir: { name: 'Kazımkarabekir' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    sariveliler: { name: 'Sarıveliler' },
  },
  71: {
    kirikkale: { name: 'Kırıkkale' },
    bahsili: { name: 'Bahşılı' },
    baliseyh: { name: 'Balışeyh' },
    celebi: { name: 'Çelebi' },
    delice: { name: 'Delice' },
    karakecili: { name: 'Karakeçili' },
    keskin: { name: 'Keskin' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    sulakyurt: { name: 'Sulakyurt' },
    yahsihan: { name: 'Yahşihan' },
  },
  72: {
    batman: { name: 'Batman' },
    besiri: { name: 'Beşiri' },
    gercus: { name: 'Gercüş' },
    hasankeyf: { name: 'Hasankeyf' },
    kozluk: { name: 'Kozluk' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    sason: { name: 'Sason' },
  },
  73: {
    sirnak: { name: 'Şırnak' },
    beytussebap: { name: 'Beytüşşebap' },
    cizre: { name: 'Cizre' },
    guclukonak: { name: 'Güçlükonak' },
    idil: { name: 'İdil' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    silopi: { name: 'Silopi' },
    uludere: { name: 'Uludere' },
  },
  74: {
    bartin: { name: 'Bartın' },
    amasra: { name: 'Amasra' },
    kurucasile: { name: 'Kurucaşile' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    ulus: { name: 'Ulus' },
  },
  75: {
    ardahan: { name: 'Ardahan' },
    cildir: { name: 'Çıldır' },
    damal: { name: 'Damal' },
    gole: { name: 'Göle' },
    hanak: { name: 'Hanak' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    posof: { name: 'Posof' },
  },
  76: {
    igdir: { name: 'Iğdır' },
    aralik: { name: 'Aralık' },
    karakoyunlu: { name: 'Karakoyunlu' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    tuzluca: { name: 'Tuzluca' },
  },
  77: {
    yalova: { name: 'Yalova' },
    altinova: { name: 'Altınova' },
    armutlu: { name: 'Armutlu' },
    cinarcik: { name: 'Çınarcık' },
    ciftlikkoy: { name: 'Çiftlikköy' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    termal: { name: 'Termal' },
  },
  78: {
    karabuk: { name: 'Karabük' },
    eflani: { name: 'Eflani' },
    eskipazar: { name: 'Eskipazar' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    ovacik: { name: 'Ovacık' },
    safranbolu: { name: 'Safranbolu' },
    yenice: { name: 'Yenice' },
  },
  79: {
    kilis: { name: 'Kilis' },
    elbeyli: { name: 'Elbeyli' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    musabeyli: { name: 'Musabeyli' },
    polateli: { name: 'Polateli' },
  },
  80: {
    osmaniye: { name: 'Osmaniye' },
    bahce: { name: 'Bahçe' },
    duzici: { name: 'Düziçi' },
    hasanbeyli: { name: 'Hasanbeyli' },
    kadirli: { name: 'Kadirli' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    sumbas: { name: 'Sumbas' },
    toprakkale: { name: 'Toprakkale' },
  },
  81: {
    duzce: { name: 'Düzce' },
    akcakoca: { name: 'Akçakoca' },
    cumayeri: { name: 'Cumayeri' },
    cilimli: { name: 'Çilimli' },
    golyaka: { name: 'Gölyaka' },
    gumusova: { name: 'Gümüşova' },
    kaynasli: { name: 'Kaynaşlı' },
    merkez: { name: 'Merkez' },
    'sehir merkezi': { name: 'Merkez' },
    yigilca: { name: 'Yığılca' },
  },
};

const getDistrict = (cityId, district) => {
  const districtName = district
    .toLocaleLowerCase('tr-TR')
    .replace(/ç/g, 'c')
    .replace(/ğ/g, 'g')
    .replace(/ı/g, 'i')
    .replace(/ö/g, 'o')
    .replace(/ş/g, 's')
    .replace(/ü/g, 'u')
    .trim();

  return DISTRICTS[cityId][districtName]['name'].toLocaleUpperCase('tr-TR');
};

export { DISTRICTS, getDistrict };
